source ~/.vim/vimrc/setup.vim
source ~/.vim/vimrc/common.vim
source ~/.vim/vimrc/vimgrep.vim
source ~/.vim/vimrc/bufferexp.vim
source ~/.vim/vimrc/zencoding.vim
source ~/.vim/vimrc/cleanup.vim
source ~/.vim/vimrc/tags.vim
source ~/.vim/vimrc/quickfix.vim
source ~/.vim/vimrc/completion.vim
source ~/.vim/vimrc/syntactic.vim
source ~/.vim/vimrc/nerdtree.vim
source ~/.vim/vimrc/map.vim
source ~/.vim/vimrc/dbext.vim
